# Generated by Django 3.2.25 on 2025-07-19 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=255)),
                ('productDes', models.TextField(max_length=5000)),
                ('price', models.FloatField()),
                ('sold_units', models.IntegerField()),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxpayment.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=5)),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxpayment.product')),
            ],
        ),
    ]
