# Generated by Django 3.2.25 on 2025-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxpayment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='purchased',
        ),
        migrations.AddField(
            model_name='buyer',
            name='purchased',
            field=models.ManyToManyField(to='pxpayment.Product'),
        ),
    ]
