# Generated by Django 3.2.25 on 2025-07-19 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pxpayment', '0002_auto_20250719_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='purchased',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxpayment.buyer')),
                ('product', models.ManyToManyField(to='pxpayment.Product')),
            ],
        ),
    ]
