# Generated by Django 5.2.4 on 2025-07-25 03:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxpayment', '0003_auto_20250719_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_units',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TransactionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxpayment.product')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_list',
            field=models.ManyToManyField(to='pxpayment.transactionitems'),
        ),
    ]
