# Generated by Django 5.2.4 on 2025-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxpayment', '0004_remove_product_sold_units_remove_transaction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitems',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
