# Generated by Django 5.2.4 on 2025-07-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxpayment', '0005_transactionitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
